### ISSUE TITLE
filter out trivial SMT lines?

### ISSUE THREAD

**Issue by jvoigtlaender** [owestphal/IOTasks-demo#5]
Does it make sense to filter out all lines of this form? 
![image](https://github.com/owestphal/IOTasks-demo/assets/5853832/010c5e0f-3297-442c-90d0-a02eb87dd53e)

Either directly during generation of the SMT code, or actually just as a "local hack" in the display inside the demo.

**Comment by jvoigtlaender** [comment]
Similarly, during the generation or just brutally during display in the demo, repeat lines could be filtered away, so that for example in the product example, these would not be repeated: 
![image](https://github.com/owestphal/IOTasks-demo/assets/5853832/e804d456-7013-4bbf-8a5a-6562d981b0d0)

**Comment by owestphal** [comment]
fmidue/IOTasks@0de0234ebfd6a3476e261fcbc0e0afe431b0313e added a conceptual `(apply simplify)` after the hard constratints. This gets rid of duplicate and trivial constraints and potentially applies additional rewrites (see [official documentation](https://microsoft.github.io/z3guide/docs/strategies/summary/#tactic-simplify)).
