### ISSUE TITLE
make ValueSet API available?

### ISSUE THREAD

**Issue by jvoigtlaender** [owestphal/IOTasks-demo#8]
I wanted to try out how the "product overflow" example behaves when the SMT solver is forbidden to choose `0` as one of the factors.

But I couldn't do this:
```haskell
      (readInput x (ints `Intersection` complement (Eq 0)) AssumeValid)
```
because of:
```shell
Main.hs:24:41: error:
    Variable not in scope:
      complement :: ValueSet Integer -> ValueSet Integer
   |
24 |       (readInput x (ints `Intersection` complement (Eq 0)) AssumeValid)
   |                                         ^^^^^^^^^^
```

**Comment by jvoigtlaender** [comment]
Side note: The line numbering from the compiler message seems off, given that the example code with line numbers was as follows.

![image](https://github.com/owestphal/IOTasks-demo/assets/5853832/3d5ee060-5ede-431a-9314-aae7e948dd8b)

**Comment by jvoigtlaender** [comment]
Also, maybe it is worth adding something like
```
(\\) :: ValueSet Integer -> ValueSet Integer -> ValueSet Integer
```
or
```
delete :: Integer -> ValueSet Integer -> ValueSet Integer
```
to the API?

(Names above are from the list API, there might be better ones.)

**Comment by owestphal** [comment]
there are now functions 
```haskell
with :: ValuesSet Integer -> Integer -> ValueSet Integer
without :: ValuesSet Integer -> Integer -> ValueSet Integer
(\\) :: ValueSet Integer -> ValueSet Integer -> ValueSet Integer
```
as well as functions for the basic constructors. (constructors are now hidden)
